
services:

  base_service:
    build: .
    working_dir: /app/
    volumes:
      - ./:/app/
    environment:
      - github_token
      - gitlab_token

  create_registry:
    extends:
      service: base_service
    command: python -u ./src/create_registry.py

  clscor_convert:
    extends:
      service: base_service
    command: python -u ./src/clscor_convert.py

  clscor_match_vocabs:
    extends:
      service: base_service
    command: python -u ./src/clscor_match_vocabs.py


