
services:

  create_registry_serial:
    extends:
      file: compose.yaml
      service: create_registry

  clscor_convert_serial:
    extends:
      file: compose.yaml
      service: clscor_convert
    depends_on:
      create_registry:
        condition: service_completed_successfully

  clscor_match_vocabs_serial:
    extends:
      file: compose.yaml
      service: clscor_match_vocabs
    depends_on:
      clscor_convert:
        condition: service_completed_successfully
